mode: "debug"
maxProc: 0

config:
  type: "local"
  watcher: true
  flagPrefixes: ["config_etcd_format"]
  envPrefixes: ["CONFIG_TYPE"]
  etcd:
    endpoints: ["localhost:2379"]
    timeout: 3
    format: "json"
    prefix: "/sapi/config"
    debug: true

logger:
  level: -2
  development: true
  logFileDir: ""
  maxSize: 500
  maxBackups: 200
  maxAge: 10

redis:
  mode: "single"
  password: "mylove1688"
  db: 0
  timeout: 3
  maxRetries: 3
  single:
    network: "tcp"
    addr: "localhost:6379"

  cluster:
    nodes: "localhost:6379,localhost:6379"

  sentinel:
    master: "master"
    nodes: "localhost:6379,localhost:6379"

  pool:
    poolSize: 0
    minIdleConns: 0

orm:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  database: "test"
  username: "root"
  password: ""
  charset: "utf8"
  prefix: "t_"
  dbFile: ""

tracer:
  driver: "jaeger"
  name: "demo"

  zipkin:
    endpointUrl: "http://192.168.16.218:9411/api/v2/spans"

  jaeger:
    mode: "server"
    endpointUrl: "http://192.168.16.233:14268/api/traces"
    userName: ""
    password: ""
    agentEndpoint: "localhost:6831"

server:
   - name: "http"
     driver: "gin"
     region: "广东"
     zone: "一区"
     groupName: "开发组"
     ip: ""
     port: 8088
   - name: "grpc"
     driver: "grpc"
     region: "广东"
     zone: "一区"
     groupName: "开发组"
     ip: ""
     port: 8089

registry:
  Timeout: 3
  TTL: 5